### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by ghost** [Teamblocket/PCFly#2]
disable fly upon level changing 

*don't u say this has nothing to do with the plugin because it does*

**Comment by brexmania123** [comment]
naa it actually doesnt
i know the owner well

**Comment by aimjel** [comment]
Now, this does actually have something todo with the plugin itself. Because, since flying is control via the plugin , level changing for fly should to.

**Comment by brexmania123** [comment]
xD

**Comment by aimjel** [comment]
https://github.com/Teamblocket/PCFly/commit/4aee199141c85f8942ea12ad6895b8f9a159a0db .
Done.
